"""Agregar pregunta y respuesta secreta a usuario

Revision ID: 06057bccb3a1
Revises: e906db0edcb3
Create Date: 2026-05-28 09:11:23.176739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06057bccb3a1'
down_revision = 'e906db0edcb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pregunta_secreta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('respuesta_secreta', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('respuesta_secreta')
        batch_op.drop_column('pregunta_secreta')

    # ### end Alembic commands ###
